sudo: false
os:
- linux
- osx
osx_image: xcode7.3
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
cache:
- directories:
  - "$HOME/.npm"
branches:
  only:
  - master
before_script:
  - nvm install stable
  - npm run lint
  - nvm use $TRAVIS_NODE_VERSION
  - npm run unit-tests
